Repository UMC-Banddy/client, pull requests merged in 2025-08, with the labels that each got.

#74 fix: 배포환경 api 호출형태 변경
  src/features/archive/hooks/useArchivedAlbums.ts
  src/features/archive/hooks/useArchivedArtists.ts
  src/features/archive/hooks/useArchivedTracks.ts
  src/features/my/hooks/useProfile.ts
  src/pages/Archive/Album/AlbumPage.tsx
  src/pages/Archive/Artist/ArtistPage.tsx
  src/pages/Archive/Music/MusicPage.tsx
  src/pages/My/MyPage.tsx
  vercel.json
Labels: bug

#77 Feat: 알림 페이지 친구 관련 api 연동
  src/features/notification/hooks/useFriendRequestActions.ts
  src/features/notification/hooks/useSendFriendRequest.ts
  src/pages/Notification/NotificationDetailPage.tsx
  src/pages/Profile/ProfileDetailPage.tsx
  src/shared/ui/atoms/Toast.tsx
  src/store/friendApi.ts
Labels: enhancement

#81 refact: 스켈레톤 UI 적용
  src/pages/My/MyPage.tsx
  src/pages/My/_components/ProfileInfoSkeleton.tsx
  src/pages/Notification/NotificationPage.tsx
  src/pages/Notification/_components/NotificationItem.tsx
  src/pages/Notification/_components/NotificationItemSkeleton.tsx
  src/pages/Notification/_components/NotificationList.tsx
  src/pages/Notification/_components/NotificationListSkeleton.tsx
  src/pages/Profile/OtherProfile.tsx
Labels: enhancement

#87 feat: 회원가입 인증번호 재전송 기능 추가 및 UI 개선
  src/pages/Signup/SignupVerifyPage.tsx
Labels: enhancement

#92 refact: 폴더 아이콘 경로 수정
  src/pages/Archive/Music/_components/ColoredFolder.tsx
Labels: enhancement

#95 feat: 개인 채팅 관련 로직 구현
  src/app/router.tsx
  src/features/setting/hooks/useAuth.ts
  src/pages/chat/PrivateChatPage.tsx
  src/pages/chat/_components/PrivateChatMessageList.tsx
  src/pages/chat/hooks/useChat.ts
  src/pages/chat/hooks/usePrivateChat.ts
  src/services/WebSocketService.ts
  src/store/auth.ts
  src/store/chatApi.ts
  src/types/chat.ts
  src/widgets/Layout/Layout.tsx
Labels: enhancement

#105 refact: 개인 채팅 페이지 UI 수정 및 바텀바 수정
  src/pages/chat/_components/PrivateChatMessageItem.tsx
  src/pages/chat/_components/PrivateChatMessageList.tsx
  src/widgets/Layout/BottomBar.tsx
Labels: enhancement

#107 fix : 리프레시 토큰 및 aws 배포 deploy 세팅
  .github/workflows/deploy-release.yml
  src/api/API.ts
  src/features/setting/hooks/useAuth.ts
  src/shared/utils/authCleanup.ts
  vercel.json
Labels: enhancement

#108 fix : dkdl
  package-lock.json
  src/api/API.ts
  src/app/router.tsx
  src/features/band/hooks/useBandData.ts
  src/pages/Band/BandDetailPage.tsx
  src/pages/Home/BandDetailPage/PeoplePage.tsx
  src/pages/Home/BandDetailPage/PlaylistPage.tsx
  src/pages/Home/BandDetailPage/PreferPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/_components/BandCarousel.tsx
  src/pages/Home/_components/BandInfoModal.tsx
  src/pages/Home/_components/ButtonSection.tsx
  src/pages/Home/_components/people/BandProfileHeader.tsx
  src/pages/pretest/artist/PretestArtistPage.tsx
  src/pages/pretest/profile/PretestProfileCompletePage.tsx
  src/pages/pretest/session/PretestSessionPage.tsx
  src/services/WebSocketService.ts
  vercel.json
  vite.config.ts
Labels: enhancement

#114 fix : TypeScript 린터 에러 수정 및 콘솔 로그 최적화
  src/pages/Home/HomePage.tsx
  src/store/userStore.ts
Labels: enhancement

#115 fix : lint errer 수정
  src/pages/Home/HomePage.tsx
  src/pages/Home/_components/BandInfoModal.tsx
  src/pages/Home/_components/TagList.tsx
  src/store/userStore.ts
Labels: enhancement

#118 doc : 4번까지 문서 수정
  README.md
Labels: documentation

#119 Feat : 메인페이지에서 join 시 rooms 및 채팅방생성/구독 + lastRead 자동 전송
  .gitignore
  src/pages/Home/HomePage.tsx
  src/pages/Join/Join.tsx
  src/pages/chat/hooks/useChat.ts
  src/pages/chat/hooks/useWebSocket.ts
  src/services/WebSocketService.ts
  src/store/chatApi.ts
  src/store/chatStore.ts
Labels: enhancement

#121 feat: eslint 에러 수정
  eslint.config.cjs
  src/pages/Home/HomePage.tsx
  src/pages/chat/hooks/useChat.ts
  src/pages/chat/hooks/usePrivateChat.ts
  src/pages/chat/hooks/useWebSocket.ts
Labels: bug

#128 feat :bookmakr & home 정보 recuitment로 불러오기
  src/features/bandBookmark/api.ts
  src/features/bandBookmark/components/BandBookmarkButton.tsx
  src/features/bandBookmark/hooks.ts
  src/features/bandBookmark/types.ts
  src/features/bandJoin/api.ts
  src/features/bandJoin/components/SessionSelectModal.tsx
  src/features/bandJoin/types.ts
  src/pages/Home/HomePage.tsx
  src/pages/Home/_components/BandCarousel.tsx
  src/pages/Home/_components/ButtonSection.tsx
  src/pages/Home/_components/MyBandCard.tsx
  src/pages/Home/_components/TagList.tsx
  src/pages/Join/_components/chat/NormalChat.tsx
  src/pages/chat/_components/ChatMessageItem.tsx
  src/pages/chat/_components/PrivateChatMessageItem.tsx
  src/pages/chat/hooks/useChat.ts
  src/pages/chat/hooks/useWebSocket.ts
  src/services/WebSocketService.ts
  src/store/chatStore.ts
  src/store/userStore.ts
  src/types/band.ts
  src/types/chat.ts
Labels: enhancement

#133 feat: 내 프로필 수정 1차 구현 및 연동
  src/api/API.ts
  src/app/router.tsx
  src/features/my/hooks/useProfileEdit.ts
  src/pages/My/_components/ProfileInfo.tsx
  src/pages/My/edit/MyEditPage.tsx
  src/pages/My/edit/_components/ArtistCard.tsx
  src/pages/My/edit/_components/ArtistSection.tsx
  src/pages/My/edit/_components/BasicInfoSection.tsx
  src/pages/My/edit/_components/GenreSection.tsx
  src/pages/My/edit/_components/IntroductionSection.tsx
  src/pages/My/edit/_components/KeywordSection.tsx
  src/pages/My/edit/_components/LocationSection.tsx
  src/pages/My/edit/_components/ProfileEditHeader.tsx
  src/pages/My/edit/_components/ProfileImageSection.tsx
  src/pages/My/edit/_components/ProfileTag.tsx
  src/pages/My/edit/_components/SessionIcon.tsx
  src/pages/My/edit/_components/SessionSection.tsx
  src/store/profileApi.ts
Labels: enhancement

#140 feat: 밴드 매니저와 지원자의 채팅 연결
  src/pages/Join/_components/chat/BandChat.tsx
  src/pages/Join/_components/chat/NormalChat.tsx
  src/pages/chat/PrivateChatPage.tsx
  src/pages/chat/hooks/usePrivateChat.ts
  src/services/WebSocketService.ts
Labels: enhancement
